NervanaSystems/distiller

- distiller/policy.py
- distiller/scheduler.py
- examples/classifier_compression/compress_classifier.py
- examples/word_language_model/main.py
- tests/test_loss.py
* Instead of a single additive value (which so far represented only the
regularizer loss), callbacks return a new overall loss
* Policy callbacks also return the individual loss components used to
calculate the new overall loss.
* Add boolean flag to the Scheduler's callback so applications can choose
if they want to get individual loss components, or just the new overall
loss
* In compress_classifier.py, log the individual loss components
* Add test for the loss-from-callback flow
> Generalize the loss value returned from before_backward_pass callbacks

- apputils/model_summaries.py
- models/__init__.py
When running inference in ONNX, we often want to add a softmax
layer to TorchVision's models.
> ONNX export: add Softmax layer to the end of image classifiers

- distiller/scheduler.py
After commit f396c34a362731c765370d368877c2ca367ad651, we
Now always apply a pruning mask at the end of mini-batches (this is
because we understand that weights may be updated by SGD+momentum,
even for weights that are masked. Therefore, there is no need for masking
the gradients: we always mask the weights at the end of the mini-batch.
See issue #53 for more details.
> Pruning: remove unnecessary backward hook used for masking gradients

- distiller/config.py
- examples/classifier_compression/compress_classifier.py
When we resume from a checkpoint, we usually want to continue using the checkpoint’s
masks.  I say “usually” because I can see a situation where we want to prune a model
and checkpoint it, and then resume with the intention of fine-tuning w/o keeping the
masks.  This is what’s done in Song Han’s Dense-Sparse-Dense (DSD) training
(https://arxiv.org/abs/1607.04381).  But I didn’t want to add another argument to
```compress_classifier.py``` for the time being – so we ignore DSD.
There are two possible situations when we resume a checkpoint that has a serialized
```CompressionScheduler``` with pruning masks:
1. We are planning on using a new ```CompressionScheduler``` that is defined in a
schedule YAML file.  In this case, we want to copy the masks from the serialized …
> Fix: Resuming from checkpoint ignored the masks stored in the checkpoint

- examples/classifier_compression/compress_classifier.py
If you invoke compress_clasifier.py with --num-best-scores=n
with n>1, then the value of best_top1 stored in checkpoints is wrong.
> Bug fix: value of best_top1 stored in the checkpoint may be wrong

- distiller/scheduler.py
- examples/classifier_compression/compress_classifier.py
- tests/full_flow_tests.py
- Bug fix for issue #79
Change the default values so that the following scheduler meta-data keys
are always defined: 'starting_epoch', 'ending_epoch', 'frequency'
- compress_classifier.py: add a new command-line argument
Allow the specification, from the command line arguments,  of the range of
pruning levels scanned when doing sensitivity analysis
- Add regression test for issue #79
> Fix Issue 79

- distiller/utils.py
Add support to models that contain named empty layers.
This solution suppresses such events, and the layer is ignored.
How to reproduce:
See the Resnet variants found on: https://github.com/Cadene/pretrained-models.pytorch
Specifically, the last FC layer
> Fix assign_layer_fq_names

- examples/classifier_compression/compress_classifier.py
Bug: quantize a model which have thining_recipe  => loading checkpoint fail
The compression scheduler did not pass and save into checkpoint when --qe -e is set
It cause loading the checkpoint file failed since the thinning_recipe should combine with compression_ scheduler
> Fix bug: --qe do not save compression scheduler

- distiller/pruning/ranked_structures_pruner.py
This patch corrects overlapping between
magnitude_fn and block_shape arguments during
block pruning.
> hotfix for broken block pruning

- examples/automated_deep_compression/ADC.py
- examples/classifier_compression/compress_classifier.py
- examples/word_language_model/main.py
"Peformance" --> "Performance"
caution: It has significant visual effect. That will mess things up a bit for you, should you try to compare plots of training sessions made prior to this patch, with new ones.
> Fix typo in tflogger path

- distiller/pruning/ranked_structures_pruner.py
Modify LpRankedStructureParameterPruner to log as
the correct class name for both L1 and L2 pruners.
> Fix logging message for structured pruning

- distiller/apputils/checkpoint.py
- distiller/config.py
- distiller/policy.py
- distiller/scheduler.py
- distiller/thinning.py
- distiller/utils.py
- examples/agp-pruning/mobilenet.imagenet.schedule_agp.yaml
- examples/agp-pruning/resnet20_filters.schedule_agp.yaml
- examples/agp-pruning/resnet20_filters.schedule_agp_2.yaml
- examples/agp-pruning/resnet20_filters.schedule_agp_3.yaml
- examples/agp-pruning/resnet20_filters.schedule_agp_4.yaml
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
- examples/network_surgery/resnet20.network_surgery.yaml
- examples/network_trimming/resnet56_cifar_activation_apoz.yaml
- examples/network_trimming/resnet56_cifar_activation_apoz_v2.yaml
- examples/pruning_filters_for_efficient_convnets/resnet56_cifar_channel_rank.yaml
- examples/pruning_filters_for_efficient_convnets/resnet56_cifar_filter_rank.yaml
- examples/pruning_filters_for_efficient_convnets/resnet56_cifar_filter_rank_v2.yaml
- examples/ssl/ssl_channels-removal_finetuning.yaml
- examples/ssl/ssl_channels-removal_finetuning_x1.8.yaml
- examples/ssl/ssl_filter-removal_training.yaml
- examples/ssl/vgg16_cifar_ssl_channels_training.yaml
- tests/test_infra.py
- tests/test_pruning.py
[ resubmitting #169 ]
This fixes long-standing bug in distiller with resuming from checkpoint.
Before this patch, the optimizer field in the checkpoint was ignored.
Although it corrects an erroneous behavior of the 'resume' flag, it is a behavioral change of dominant functionality.
A few thoughts before merging into master:
Documentation: This patch does not contain required changes to Distiller online documentation.
Insufficient tests: None of current tests caught that bug, nor I address this matter in my patch.
I tested it briefly with the attached steplr lr_sched recipe, and enjoyed using it, but don't trust me on this - test for yourself. I have no idea how it plays with quantization, gpu<-->cpu transitions, or non-sgd optimizers.
examples change: In the patch I added a flag that …
> Load optimizer

- distiller/summary_graph.py
- tests/test_summarygraph.py
This fixes issue #213.
Dropout layers were not handled properly in SummaryGraph, and
caused the indexing of layer names to change.
The root cause is that in ONNX node names are composed of (roughly)
three parts: the node name, type, and instance.
In SummaryGraph we ignore the node type when naming a node.
Specifically in AlexNet, nodes the Dropout layers before a Linear
layer have the same node name and instance, and are only distinguished
by their type.  SummaryGraph, ignorant of the type, skipped the Dropout
layers and gave nodes the wrong name.  Thus 'classifier.0', which is
a Dropout node, became a Linear node.
The fix is not to ignore duplicate (node name, instance) pairs
by incrementing the instance.
> Fix issue #213

- examples/word_language_model/generate.py
- tests/common.py
- tests/test_basic.py
- tests/test_learning_rate.py
- tests/test_loss.py
- tests/test_model_summary.py
- tests/test_post_train_quant.py
- tests/test_pruning.py
- tests/test_quant_utils.py
- tests/test_quantizer.py
- tests/test_ranking.py
- tests/test_thresholding.py
Removed `sys.path` modifications when importing distiller.
#215
> Remove sys.path modifications

- distiller/summary_graph.py
- distiller/thinning.py
- tests/test_summarygraph.py
This patch lifts the need to convert the layer name back and forth with utils.{de,}normalize_module_name() while using summary graph.
Added named_params_layers utility method to summary graph that yields a 3-tuple of: layer name, param name, and param.
When using the new method, summary graph communicates the true layer name in respect to the model it was initiated with.
Ran pytest locally and it passed.
> Clean-up summary_graph API

- distiller/data_loggers/logger.py
- distiller/model_summaries.py
- distiller/utils.py
- Add functionality to log values of buffers in a model - in all logger types (PythonLogger, TensorBoardLogger, CSVLogger). Exact behavior varies per logger type and documented in the code.
- To enable this in the CSV logger, changed its API to take a file name prefix (optionally empty) instead of the full name, and use a hard-coded name for logging weights sparsity.
- Also fixed signature of `log_training_progress` in base DataLogger class to match the signature used in the sub-classes
> Add functionality to log values of buffers in a model

- distiller/apputils/checkpoint.py
- distiller/pruning/greedy_filter_pruning.py
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/inspect_ckpt.py
'best_top1' is too specific to classification workloads. Suggesting to just pass a dictionary of values instead, which will allow to pass anything the user deems worthy.
Also modified `load_checkpoint` to print a summary of the checkpoint contents, it looks something like this:
```
=> loading checkpoint logs/2019.04.04-131231/checkpoint.pth.tar
=> Checkpoint contents:
+----------------------+----------------+
| Key                  | Type / Value   |
|----------------------+----------------|
| arch                 | resnet20_cifar |
| best_epoch           | 1              |
| best_top1            | 58.06          |
| compression_sched    | dict           |
| current_top1         | 53.18          |
| epoch                | 2              |
| optimizer_state_dict | dict           |
| …
```
> (BREAKING) save_checkpoint(): Save dict of user values instead of best_top1

- distiller/apputils/data_loaders.py
- distiller/utils.py
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
- tests/full_flow_tests.py
Due to Pytorch's implementation of dataset loading, it is
_required_ to use single loading-worker in order to achieve
deterministic results. [1]
Since the user is not expected to be familiar with all the
quirks of deterministic execution, this patch lifts the
requirement for the user to set the number of workers to 1,
it does that automatically instead.
Another change that introduced here is that evaluation of
a model will be always deterministic.
Decreasing the number of workers **slows down** the evaluation.
Minor changes:
- utils.set_deterministic sets cudnn.benchmark as required [2]
- data_loaders.get_data_loaders enforces determinism correctly
- correct '--evaluate' help string
[1] - https://petewarden.com/2018/03/19/the-machine-learning-reproducibility-crisis/
[2] - …
> Simplify deterministic evaluation

- tests/test_infra.py
In former commit, distiller accept checkpoints that do not contain
'optimizer' argument. However, this change was not reflected in the
relevant test.
> Fix broken load test

- distiller/apputils/data_loaders.py
- distiller/data_loggers/collector.py
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
- jupyter/activation_histograms.ipynb
- jupyter/distiller_jupyter_helpers.ipynb
- jupyter/logging.conf
Added a collector for activation histograms (sub-class of `ActivationStatsCollector`).
It is stats-based, meaning it requires pre-computed min/max stats per tensor. This is done in order to prevent the need to save all of the activation tensors throughout the run. The stats are expected in the format generated by `QuantCalibrationStatsCollector`.
Details:
* Implemented ActivationHistogramsCollector
* Added Jupyter notebook showcasing activation histograms
* Implemented helper function that performs the stats collection pass and histograms pass in one go
* Also added separate helper function just for quantization stats collection
* Integrated in image classification sample
* data_loaders.py: Added option to have a fixed subset throughout within the same session. Using it to keep the same …
> Activation Histograms

- distiller/apputils/execution_env.py
Log all pip packages instead of doing so selectively.
Listing all the packages might sound a bit excessive, but I prefer that over keeping track on each environment variable that might/not affect the user's experience, and statically add it to the logging function.
> Log "pip freeze"

- distiller/utils.py
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
Added set_seed() to Distiller (utils.py) and added support for seeding the PRNG,
in both reproducible and non-reproducible modes.
The PRNGs of Pytorch (CPU & Cuda devices), numpy and Python are set.
Added support for ```--seed``` to classifier_compression.py.
> Added support for setting the PRNG seed

- distiller/quantization/quantizer.py
- tests/test_quantizer.py
Fixed bug where a shared module which was supposed to be skipped wasn't skipped on the second reference.
> Bug fix for shared module

- distiller/quantization/range_linear.py
* Removed RuntimeError when using nn.DataParallel with QuantAwareTrainRangeLinearQuantizer
Training with FakeLinearQuantization using Multi GPU is working after upgrading to PyTorch 1.0.1
> DataParallel for QuantAwareTrainRangeLinearQuantizer

- distiller/pruning/greedy_filter_pruning.py
After  `del zeros_mask_dict` is called, you use `zeros_mask_dict` again and error arose.
> fix bug of greedy filter pruning

- distiller/apputils/data_loaders.py
- distiller/models/__init__.py
- distiller/utils.py
Setting this attribute will become a requirement for some upcoming features
* Add utility function to set input_shape attribute in models
* Set this attribute in the classification models factory `distiller.models.create_model()`
* Add shape parameter in get_dummy_input (in addition to dataset)
> Input shape attribute in models

- distiller/model_summaries.py
Allow drawing models to images for unsupported datasets via `input_shape` argument
> Added `input_shape` argument to `draw_img_classifier_to_file`

- distiller/summary_graph.py
- tests/test_summarygraph.py
* Adjacency map - map from each op to its predecessor and successor ops
* More robust handling of Gemm nodes scope names (instead of
increment_instance())
* More consistent handling of ops with the same scope name
* Handle pad + avg pool sequences generated by ONNX trace optimization
(results in one less op in the graph, hence the changes in tests)
* Minor refactoring in predecessors() and successors() functions
> SummaryGraph: Adjacency map + numerous changes

- distiller/apputils/checkpoint.py
- distiller/data_loggers/collector.py
Change the default checkpoint loading behavior, such that we allow
loading a checkpoint that has state-dict entries that do not
appear in the original (Distiller) model.
> Allow loading checkpoints with superfluous state-keys

- requirements.txt
tensorboard 1.14 is required to take advantage of Pytorch's exp. implementation of summarywriter.
(It wasn't stable yet when I pushed the Pytorch 1.1 initial commit)
> Increase Tensorflow min version to 1.14

- distiller/quantization/range_linear.py
For some reason, SummaryGraph generation is broken for DistillerLSTM modules with 'bidirectional' enabled. The ONNX graph optimization stage causes all the nodes from the bidirectional module to vanish from the graph (they're in the graph after the initial trace)
As a temporary workaround to enable stats fusion in post-train quant, if a bidirectional DistillerLSTM is detected, we just do a simple "hard-coded" fusion of the element-wise add op with the subsequent non-linearities and skip the automatic flow with SummaryGraph.
> Post-train quant: Special handling for bi-directional DistillerLSTM

- distiller/summary_graph.py
- tests/test_summarygraph.py
By duplicate modules we mean:
```python
self.relu1 = nn.Relu()
self.relu2 = self.relu1
```
* The issue: The second module ('relu2') will not be returned by `torch.nn.Module.named_modules/children()`
* When converting to DistillerModuleList, in order to maintain the original order of modules and in order to have a correct mapping of names before/after the conversion - we need to take the duplicates into account.
* Implemented an internal version of `named_modules/children` that includes duplicates
* Added test case for this + refactored the module list conversion tests
> DistillerModuleList conversion: Handle models with duplicate modules

- distiller/pruning/ranked_structures_pruner.py
- distiller/thresholding.py
I made these changes to work with the L1RankedStructureParameterPruner_AGP class. The network gets pruned and there are no errors.
The sparsity summary shows 2D/3D pruning only on the 4D filter (screenshot included), I don't know if that's normal.
> LpRankedStructureParameterPruner: work with 3D filters (ie Conv1d)

- distiller/quantization/clipped_linear.py
Long overdue fix for #260 
Our original implementation "manually" calculated the gradients of the activations with respect to the clipping value. In fact, we can use built-in PyTorch functions and let autograd do the hard work, and the resulting gradient is exactly as expected. So there's no need for a the dedicated `LearnedClippedLinearQuantizeSTE` function. The new implementation re-uses the simpler `LinearQuantizeSTE`. Compared to DoReFa, the new PACT implementation has a 2 extra operations in forward (calculating the scale factor and zero point) and 1 extra operation in backwards (calculating the gradient with respect to the clipping value - via autograd).
Overall the new implementation is up to 2x faster compared to the previous implementation (depends on the exact hyper params …
> Faster implementation of PACT

- distiller/quantization/range_linear.py
Registered `is_simulated_quant_weight_shifted` as a tensor buffer so quantizing asymmetrically in PostTrainQuantization doesn't break the model.
> Fix Asymmetric treatment to enable nn.DataParallel

- distiller/apputils/image_classifier.py
This patch moves the check on remaining training epochs into the training loop, as it is irrelevant for non-training invocation of ClassifierCompressor.
Thus, allowing resumed checkpoints be evaluated regardless of the epochs limitation.
> Fix epochs limitation check

- distiller/apputils/image_classifier.py
- distiller/data_loggers/__init__.py
- distiller/data_loggers/logger.py
- distiller/models/__init__.py
- jupyter/tutorial__adding_new_model.ipynb
Add a jupyter notebook showing how to register a user's (external) image-classification model.
Contains fixes to the previous models extension mechanism, and relaxation of the `args' requirements in apputils/image_classifier.py.
apputils/image_classifier.py –
*when self.logdir is None:
-use NullLogger
-skip save_checkpoint
*return training log from run_training_loop()
*don’t log if script_dir or output_dir are not set.
*Fix params_nnz_cnt in update_training_scores_history()
data_loggers/logger.py – add NullLogger which does not log
> User-registered model

- distiller/quantization/clipped_linear.py
- distiller/quantization/quantizer.py
* Create float copy such that the actual tensor being learned stays the same
* This way the optimizer doesn't have to be re-created, just need to add parameter groups if algo requires it (e.g. PACT)
* This also means we don't care about pre-existing parameter groups, as opposed to the previous implementation which **assumed** a single existing group
> Quant-aware training: Better handling of optimizer and creation of float weights copy

- requirements.txt
Hot-fix for issue that arises with FileWriter class on TF v2.
Allows only Tensorflow v1.X
For more details on the change: https://www.tensorflow.org/tensorboard/migrate
> Change requirements on Tensorflow version

- distiller/quantization/quantizer.py
Added note in `Quantizer` class that overrides layer names should come in their un-`dataparallel`-ized versions.
> Clarify usage of Quantizer overrides with DataParallel

- distiller/data_loggers/collector.py
- examples/classifier_compression/inspect_ckpt.py
Pointed out by @Pavelrst :)
Standard deviation calculation was calculated with an average over batches, where the last batch might be very small and hence less elements.  
Corrected by calculating std in the second pass by definition (after `mean` was calculated) .
> Correct handling of different batch-sizes in collectors

- distiller/models/__init__.py
- distiller/models/imagenet/resnet.py
Changed our version to only re-implement BasicBlock and Bottleneck,
and duplicate the model creation functions. Other than that, re-use
everything from the torchvision implementation.
> Update internal ResNet implementation according to latest TorchVision

- distiller/quantization/ptq_greedy_search.py
- distiller/quantization/range_linear.py
- tests/test_post_train_quant.py
get/set ops for scale& zero_point in `RangeLinearQuantWrapper`s.  
At the moment only the activations are supported, might add inputs+weights later
> Exposed get/set ops for quantization params

- distiller/quantization/range_linear.py
- examples/quantization/post_train_quant/command_line.md
- tests/test_post_train_quant.py
Same functionality as #356, but decided to take a different approach, which reuses the existing PTQ wrapper modules. This reduces code duplication and keeps the quantized model "similar" (in terms of modules used) when activations aren't quantized vs. when they are.
* Allow `RangeLinearQuantWrapper` to accept `num_bits_acts = None`, in which case it'll act as a simple pass-through during forward.
* In `RangeLinearQuantParamLayerWrapper`, if `bits_activations` is None and `num_bits_params` > 0, perform quant and de-quant of the parameters instead of just quant.
* Enable activations only quantization for conv/linear modules. When `PostTrainLinearQuantizer` detects # bits != None for activations and # bits == None for weights, a fake-quantization wrapper will be used.
* Allow passing 0 in …
> Enable weights-only and activations-only post-training quantization for conv/linear modules

- distiller/apputils/image_classifier.py
- distiller/data_loggers/collector.py
Patch adds support to collecting IFM sparsity, as well as multiple IFMs. If multiple IFMs are present, they are merged with `torch.cat`, which is a parameter to the collector.
IFM sparsity will be collected whenever activation sparsity is collected with `create_activation_stats_collectors`.
Renamed some of the fields/filenames.
Tested against Python3.6. Passed ~~excluding the post-training tests.~~ (merged @guyjacob bugfix)
Note the use of typing library for type hinting. Not sure about the state of support for this in older Python 3.5 environments. It's possible that this patch requires Python3.6 OR Python3.5+updates, but not sure how to check that.
> IFM sparsity collector

- distiller/quantization/__init__.py
- distiller/quantization/ptq_greedy_search.py
- distiller/quantization/q_utils.py
- distiller/quantization/range_linear.py
* Fake quant wrapper now also works on (fake) quantized inputs
* Remove 'requires_quantized_inputs' flag
* Unrelated: Moved LinearQuantMode enum to q_utils
> PTQ: Refactor inputs quantization

- distiller/apputils/image_classifier.py
- distiller/quantization/ptq_coordinate_search.py
- distiller/quantization/range_linear.py
- examples/classifier_compression/README.md
- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
- examples/classifier_compression/ptq_lapq.py
- examples/quantization/post_train_quant/command_line.md
- examples/quantization/post_train_quant/resnet18_imagenet_post_train_lapq.yaml
* Move image classification specific setup code to separate script at `examples/classifier_compression/ptq_lapq.py`
* Make ptq_coordinate_search function completely independent of command line arguments
* Change LAPQ command line args function to update existing pre-existing parser (changed CLAs perfix to 'lapq' for more clarity)
* Enable LAPQ from compress_classifier.py (trigger with `--qe-lapq`)
* Add pointers in documentation
> Post-Train Quant LAPQ Refactoring
