- apputils/model_summaries.py
- examples/classifier_compression/compress_classifier.py
- tests/test_summarygraph.py
* Modify 'create_png' to use the correct data structures (dicts instead lists, etc.)
* Handle case where an op was called not from a module. This relates to:
* ONNX->"User-Friendly" name conversion to account for cases where
* Detection of existing op with same name
In both cases use the ONNX op type in addition to the op name
* Return an "empty" shape instead of None when ONNX couldn't infer a parameter's shape
* Expose option of PNG summary with parameters to user
> Make PNG summary compatible with latest SummaryGraph class changes

- distiller/model_summaries.py
Addressing issues raised in PR #16
> Changes to weights sparsity summary

- distiller/quantization/clipped_linear.py
Modification similar to #17 to allow experimentation with WRPNQuantizer.
> Allow quantize_bias to work in WRPNQuantizer

- distiller/pruning/magnitude_pruner.py
- tests/common.py
- tests/test_pruning.py
MagnitudeParameterPruner: document and test
This is in response to a question in issue #19
> Mag pruner doc

- distiller/thresholding.py
- tests/test_thresholding.py
See issue #39 for a description of the bug from @vinutah.
> Fix bug: thresholding matrix cols should use dim=0 (issue #39)

- examples/classifier_compression/compress_classifier.py
We don't need this anymore and PyTorch 1.0 is just around the corner.
> Clean up PyTorch 0.3 compatibility code

- distiller/quantization/range_linear.py
Fix bug: error when loading SymmetricLinearQuantizer
> Fix bug: Loading the SymmetricLinearQuantizer 

- distiller/config.py
- distiller/pruning/__init__.py
- distiller/pruning/automated_gradual_pruner.py
- distiller/pruning/ranked_structures_pruner.py
- examples/agp-pruning/resnet20_filters.schedule_agp.yaml
- examples/agp-pruning/resnet20_filters.schedule_agp_2.yaml
- models/__init__.py
Using the automatic gradual pruning for structured-pruning is very
simple to use and produces good results.
It is implemented in Google's TensorFlow framework.
> AGP for structs

- examples/classifier_compression/compress_classifier.py
update the example arguments of earlyexit which were not consistent with descriptions
> Update example arguments of earlyexit

- examples/classifier_compression/compress_classifier.py
Revert back to Pytorch 0.4.0. Also fixed some numpy calls (for statistics) that needed to be moved back to CPU.
> Earlyexit statsfix

- examples/classifier_compression/compress_classifier.py
- examples/classifier_compression/parser.py
- models/__init__.py
* Move parser to its own file
* Enhance API to support more activation logging options
* Case-insensitive arguments
> Parser Cleanup

- distiller/quantization/clipped_linear.py
- distiller/quantization/q_utils.py
I try to add `BinaryQuantizeSTE` to support handling for 1-bit weights.
> Dorefa1 bit

- apputils/execution_env.py
- examples/classifier_compression/compress_classifier.py
Store configuration files (args.compress) in the output directory, under 'configs' sub-directory.
> Store config files in logdir

- distiller/apputils/execution_env.py
small fix. not very important.
The destination of the os.path.exists() call was incorrect, so the result was inconsistent.
> Fix if_file_exists check on config file

- jupyter/alexnet_insights.ipynb
Hi, I found in jupyter notebook code ( `jupyter/alexnet_insights.ipynb`  ), and I fixed it.
> fix lack of paranthesis in alexnet_insights.ipynb

- distiller/models/__init__.py
- requirements.txt
- tests/test_infra.py
Edited create_model() to import models from pretrainedmodels.
Added tests to the same function.
> Integrate Cadene pretrainedmodels [fixes #142]

- distiller/config.py
Raise error if scheduler dict contains invalid class arguments.
Until now this would be ignored, yielding unexpected results, such as what we saw in issue #191.
> Strict arguments check for scheduler dicts

- distiller/summary_graph.py
- distiller/utils.py
Added `distiller.utils.convert_recursively_to` , replaced `_treetuple2device in SummaryGraph with it.`
> Added distiller.utils.convert_recursively_to

- distiller/quantization/range_linear.py
Added FP16Wrapper, Added FP16 support in PostTrainLinearQuantizer
> Add FP16 support

- distiller/quantization/clipped_linear.py
This PR is about #198 .
Fix `DorefaParamsBinarizationSTE` and Delete docstring about 1 bit special handling.
> 198 dorefa binarization

- distiller/data_loggers/collector.py
Fixed `RuntimeError` when viewing a non-contiguous tensor
> Fix collector update_record 

- distiller/quantization/range_linear.py
* Fixed the device of the scaling tensors
> Fix the device of the scaling tensors

- distiller/data_loggers/collector.py
- examples/classifier_compression/compress_classifier.py
Return file name from ActivationStatsCollector.save() and print it.
~~**Edit**: added pretrainedmodels Resnext101 support~~
> Improved logging when saving collectors data

- distiller/modules/__init__.py
- distiller/modules/rnn.py
This functions replaces all `nn.LSTM` and `nn.LSTMCell` in the model to a `DistillerLSTM[Cell]`.
> Added replace_lstm_recursively

- distiller/apputils/execution_env.py
- examples/classifier_compression/compress_classifier.py
Stores the qe_stats_file, under configs.
Extend log_execution_env_state to accept
list of configuration files.
> Store qe_stats_file in output directory

- distiller/apputils/checkpoint.py
- distiller/quantization/quantizer.py
> Added a patch to fix issue with resuming PTQ

- distiller/apputils/image_classifier.py
- distiller/data_loggers/logger.py
- distiller/utils.py
> Fix typo: statsitic --> statistic

- distiller/apputils/image_classifier.py
- distiller/quantization/ptq_greedy_search.py
- examples/auto_compression/amc/parallel-finetune.py
- examples/classifier_compression/compress_classifier.py
Based on @barrh's #420 + fixes to usages of `ClassifierCompressor` to work with the fix
> Bugfix: Deepcopy args when creating ClassifierCompressor

- distiller/apputils/__init__.py
- distiller/apputils/image_classifier.py
- distiller/apputils/performance_tracker.py
Introduce a performance tracking class
This will help define and use different performance sorting schemes.
E.g. this will address the issue raised in issue #411
> Perf tracker

- examples/classifier_compression/compress_classifier.py
With classifier.acts_quant_stats_collection(), no stats file is saved default.
> fix error about exporting stats file of quant

- README.md
- examples/GNMT/README.md
- examples/README.md
- examples/classifier_compression/README.md
- examples/ncf/README.md
- examples/word_language_model/README.md
* Make it easier to find sample apps for different workload types
* Add READMEs for sample apps the didn't have any
* Update readmes with experiment results where applicable
> Update Examples Documentation

- distiller/quantization/range_linear.py
- examples/quantization/post_train_quant/command_line.md
- examples/quantization/post_train_quant/resnet18_imagenet_post_train.yaml
- examples/quantization/post_train_quant/resnet18_imagenet_post_train_input_overrides.yaml
In `PostTrainLinearQuantizer` and `QuantAwareTrainRangeLinearQuantizer`
> Enable setting separate LinearQuantMode for weights/activations
